export * from './Dashboard'
export * from './Device'
export * from './Generals'
export * from './Login'
export * from './Progression'
export * from './Report'
export * from './Services'
export * from './SystemSettings'